import { PatientData } from "@/shared/types/patient";

// Sample patients designed to demonstrate the two-layer approach:
// 1. LLM Intelligence (medical guidelines in system prompt)
// 2. Database Validation (drug interactions, contraindications, allergy mappings)

export const samplePatients: {
  label: string;
  description: string;
  riskPreview: string;
  demonstratesFeature: string;
  data: PatientData;
}[] = [
  // ============================================
  // DRUG-DRUG INTERACTION DEMOS
  // ============================================
  {
    label: "💀 James Wilson - CRITICAL (Nitrate + ED Meds)",
    description: "Patient on nitroglycerin requesting erectile dysfunction treatment",
    riskPreview: "CRITICAL - Contraindicated drug combination",
    demonstratesFeature: "DB: Sildenafil + Nitroglycerin = fatal hypotension risk",
    data: {
      firstName: "James",
      lastName: "Wilson",
      dateOfBirth: "1960-05-20",
      sex: "male",
      conditions: ["Coronary Artery Disease", "Angina", "Hypertension"],
      allergies: [],
      familyHistory: ["Heart disease"],
      surgicalHistory: ["Cardiac catheterization (2022)"],
      currentMedications: [
        { name: "Nitroglycerin", dosage: "0.4mg", frequency: "as needed for chest pain" },
        { name: "Atenolol", dosage: "50mg", frequency: "once daily" },
        { name: "Aspirin", dosage: "81mg", frequency: "once daily" },
      ],
      healthMetrics: {
        age: 64,
        weight: 88,
        height: 175,
        bloodPressureSystolic: 135,
        bloodPressureDiastolic: 82,
        heartRate: 68,
        bloodGlucose: 105,
      },
      lifestyle: {
        smokingStatus: "former",
        alcoholUse: "occasional",
        exerciseFrequency: "light",
        dietType: "Low fat diet",
        sleepHours: 7,
      },
      primaryComplaint: "Erectile dysfunction",
      complaintDuration: "6 months",
      complaintSeverity: "moderate",
      additionalNotes: "Wants Viagra or similar. Has stable angina controlled with nitroglycerin PRN.",
    },
  },
  {
    label: "⚠️ Margaret Brown - HIGH (Warfarin + Aspirin)",
    description: "Anticoagulated patient also on aspirin - major bleeding risk",
    riskPreview: "HIGH RISK - Major drug interaction (bleeding)",
    demonstratesFeature: "DB: Warfarin + Aspirin = significantly increased bleeding risk",
    data: {
      firstName: "Margaret",
      lastName: "Brown",
      dateOfBirth: "1958-11-12",
      sex: "female",
      conditions: ["Atrial Fibrillation", "History of DVT", "Osteoarthritis"],
      allergies: [],
      familyHistory: ["Stroke"],
      surgicalHistory: ["Knee replacement (2019)"],
      currentMedications: [
        { name: "Warfarin", dosage: "5mg", frequency: "once daily" },
        { name: "Aspirin", dosage: "325mg", frequency: "once daily" },
        { name: "Diltiazem", dosage: "180mg", frequency: "once daily" },
      ],
      healthMetrics: {
        age: 66,
        weight: 72,
        height: 160,
        bloodPressureSystolic: 128,
        bloodPressureDiastolic: 78,
        heartRate: 72,
        bloodGlucose: 95,
      },
      lifestyle: {
        smokingStatus: "never",
        alcoholUse: "none",
        exerciseFrequency: "light",
        dietType: "Regular diet",
        sleepHours: 7,
      },
      primaryComplaint: "Joint pain management",
      complaintDuration: "3 months",
      complaintSeverity: "moderate",
      additionalNotes: "Knee pain worsening. Current pain management inadequate. Looking for additional options.",
    },
  },
  {
    label: "⚠️ Lisa Chen - HIGH (SSRI + Triptan)",
    description: "Patient on sertraline with migraines taking sumatriptan",
    riskPreview: "HIGH RISK - Serotonin syndrome risk",
    demonstratesFeature: "DB: Sertraline + Sumatriptan = serotonin syndrome",
    data: {
      firstName: "Lisa",
      lastName: "Chen",
      dateOfBirth: "1985-03-28",
      sex: "female",
      conditions: ["Major Depressive Disorder", "Chronic Migraine", "Anxiety"],
      allergies: ["Penicillin"],
      familyHistory: ["Depression", "Migraine"],
      surgicalHistory: [],
      currentMedications: [
        { name: "Sertraline", dosage: "150mg", frequency: "once daily" },
        { name: "Sumatriptan", dosage: "100mg", frequency: "as needed for migraines" },
      ],
      healthMetrics: {
        age: 39,
        weight: 65,
        height: 163,
        bloodPressureSystolic: 118,
        bloodPressureDiastolic: 74,
        heartRate: 70,
        bloodGlucose: 88,
      },
      lifestyle: {
        smokingStatus: "never",
        alcoholUse: "occasional",
        exerciseFrequency: "moderate",
        dietType: "Vegetarian",
        sleepHours: 6,
      },
      primaryComplaint: "Increased migraine frequency",
      complaintDuration: "2 months",
      complaintSeverity: "severe",
      additionalNotes: "Migraines now 3-4 times per week. Sumatriptan helps but concerned about frequent use.",
    },
  },
  {
    label: "⚠️ Robert Martinez - HIGH (Clopidogrel + Omeprazole)",
    description: "Post-stent patient on clopidogrel with GERD on omeprazole",
    riskPreview: "HIGH RISK - Reduced antiplatelet efficacy",
    demonstratesFeature: "DB: Clopidogrel + Omeprazole = reduced drug activation",
    data: {
      firstName: "Robert",
      lastName: "Martinez",
      dateOfBirth: "1965-07-15",
      sex: "male",
      conditions: ["Coronary Artery Disease", "Post-PCI with stent", "GERD", "Hyperlipidemia"],
      allergies: [],
      familyHistory: ["Heart attack", "Diabetes"],
      surgicalHistory: ["Coronary stent placement (2023)"],
      currentMedications: [
        { name: "Clopidogrel", dosage: "75mg", frequency: "once daily" },
        { name: "Omeprazole", dosage: "20mg", frequency: "once daily" },
        { name: "Atorvastatin", dosage: "80mg", frequency: "once daily" },
        { name: "Aspirin", dosage: "81mg", frequency: "once daily" },
      ],
      healthMetrics: {
        age: 59,
        weight: 90,
        height: 178,
        bloodPressureSystolic: 132,
        bloodPressureDiastolic: 80,
        heartRate: 72,
        bloodGlucose: 110,
      },
      lifestyle: {
        smokingStatus: "former",
        alcoholUse: "occasional",
        exerciseFrequency: "moderate",
        dietType: "Heart-healthy diet",
        sleepHours: 7,
      },
      primaryComplaint: "Persistent heartburn despite treatment",
      complaintDuration: "4 weeks",
      complaintSeverity: "moderate",
      additionalNotes: "Heartburn not fully controlled on current PPI. Would like stronger treatment.",
    },
  },

  // ============================================
  // CONTRAINDICATION BY CONDITION DEMOS
  // ============================================
  {
    label: "💀 Frank Thompson - CRITICAL (ED + Recent Heart Attack)",
    description: "Patient had heart attack 2 months ago requesting ED treatment",
    riskPreview: "CRITICAL - Absolute contraindication (recent MI)",
    demonstratesFeature: "DB: Sildenafil contraindicated within 90 days of MI",
    data: {
      firstName: "Frank",
      lastName: "Thompson",
      dateOfBirth: "1962-09-08",
      sex: "male",
      conditions: ["Recent Myocardial Infarction (2 months ago)", "Hypertension", "Type 2 Diabetes"],
      allergies: [],
      familyHistory: ["Heart disease", "Diabetes"],
      surgicalHistory: ["Emergency cardiac catheterization (2 months ago)"],
      currentMedications: [
        { name: "Metoprolol", dosage: "50mg", frequency: "twice daily" },
        { name: "Lisinopril", dosage: "10mg", frequency: "once daily" },
        { name: "Atorvastatin", dosage: "40mg", frequency: "once daily" },
        { name: "Metformin", dosage: "500mg", frequency: "twice daily" },
      ],
      healthMetrics: {
        age: 62,
        weight: 95,
        height: 180,
        bloodPressureSystolic: 128,
        bloodPressureDiastolic: 78,
        heartRate: 65,
        bloodGlucose: 140,
      },
      lifestyle: {
        smokingStatus: "former",
        alcoholUse: "none",
        exerciseFrequency: "light",
        dietType: "Cardiac rehab diet",
        sleepHours: 6,
      },
      primaryComplaint: "Erectile dysfunction",
      complaintDuration: "2 months",
      complaintSeverity: "moderate",
      additionalNotes: "ED started after heart attack. Doctor cleared for light activity. Wants to restore intimacy.",
    },
  },
  {
    label: "⚠️ Patricia Davis - HIGH (Severe Heart Failure + ED Request)",
    description: "Patient with severe heart failure (EF 25%) requesting ED treatment",
    riskPreview: "HIGH RISK - Severe heart failure contraindication",
    demonstratesFeature: "DB: Sildenafil contraindicated in severe heart failure",
    data: {
      firstName: "Patricia",
      lastName: "Davis",
      dateOfBirth: "1970-01-25",
      sex: "female",
      conditions: ["Severe Heart Failure (EF 25%)", "Cardiomyopathy", "Hypertension"],
      allergies: ["Sulfa drugs"],
      familyHistory: ["Heart failure", "Sudden cardiac death"],
      surgicalHistory: ["ICD implantation (2022)"],
      currentMedications: [
        { name: "Carvedilol", dosage: "25mg", frequency: "twice daily" },
        { name: "Sacubitril-Valsartan", dosage: "97/103mg", frequency: "twice daily" },
        { name: "Spironolactone", dosage: "25mg", frequency: "once daily" },
        { name: "Furosemide", dosage: "40mg", frequency: "once daily" },
      ],
      healthMetrics: {
        age: 54,
        weight: 70,
        height: 165,
        bloodPressureSystolic: 105,
        bloodPressureDiastolic: 68,
        heartRate: 72,
        bloodGlucose: 92,
      },
      lifestyle: {
        smokingStatus: "never",
        alcoholUse: "none",
        exerciseFrequency: "sedentary",
        dietType: "Low sodium, fluid restricted",
        sleepHours: 6,
      },
      primaryComplaint: "Sexual dysfunction - decreased libido and arousal",
      complaintDuration: "1 year",
      complaintSeverity: "moderate",
      additionalNotes: "Quality of life affected. Wants to discuss treatment options despite heart condition.",
    },
  },

  // ============================================
  // ALLERGY CROSS-REACTIVITY DEMOS
  // ============================================
  {
    label: "🔶 Michael Adams - MEDIUM (Penicillin Allergy)",
    description: "Patient with documented penicillin allergy needing antibiotics",
    riskPreview: "MEDIUM RISK - Allergy cross-reactivity consideration",
    demonstratesFeature: "DB: Penicillin allergy cross-reacts with amoxicillin, some cephalosporins",
    data: {
      firstName: "Michael",
      lastName: "Adams",
      dateOfBirth: "1978-12-03",
      sex: "male",
      conditions: ["Sinusitis", "Seasonal Allergies"],
      allergies: ["Penicillin (hives and swelling)"],
      familyHistory: [],
      surgicalHistory: [],
      currentMedications: [
        { name: "Loratadine", dosage: "10mg", frequency: "once daily" },
      ],
      healthMetrics: {
        age: 46,
        weight: 82,
        height: 180,
        bloodPressureSystolic: 122,
        bloodPressureDiastolic: 78,
        heartRate: 72,
        bloodGlucose: 95,
      },
      lifestyle: {
        smokingStatus: "never",
        alcoholUse: "occasional",
        exerciseFrequency: "moderate",
        dietType: "Regular diet",
        sleepHours: 7,
      },
      primaryComplaint: "Sinus infection - bacterial",
      complaintDuration: "10 days",
      complaintSeverity: "moderate",
      additionalNotes: "Started as cold, now thick yellow discharge, facial pressure. Failed OTC treatment. Needs antibiotic.",
    },
  },
  {
    label: "🔶 Sandra Lee - MEDIUM (NSAID/Aspirin Allergy)",
    description: "Patient with aspirin allergy needing pain management",
    riskPreview: "MEDIUM RISK - NSAID cross-reactivity",
    demonstratesFeature: "DB: Aspirin allergy cross-reacts with ibuprofen, naproxen, NSAIDs",
    data: {
      firstName: "Sandra",
      lastName: "Lee",
      dateOfBirth: "1982-06-18",
      sex: "female",
      conditions: ["Osteoarthritis", "Asthma"],
      allergies: ["Aspirin (bronchospasm)", "NSAIDs"],
      familyHistory: ["Asthma", "Arthritis"],
      surgicalHistory: [],
      currentMedications: [
        { name: "Albuterol inhaler", dosage: "2 puffs", frequency: "as needed" },
        { name: "Fluticasone inhaler", dosage: "250mcg", frequency: "twice daily" },
      ],
      healthMetrics: {
        age: 42,
        weight: 68,
        height: 165,
        bloodPressureSystolic: 118,
        bloodPressureDiastolic: 72,
        heartRate: 70,
        bloodGlucose: 90,
      },
      lifestyle: {
        smokingStatus: "never",
        alcoholUse: "none",
        exerciseFrequency: "light",
        dietType: "Anti-inflammatory diet",
        sleepHours: 7,
      },
      primaryComplaint: "Chronic knee pain from arthritis",
      complaintDuration: "6 months",
      complaintSeverity: "moderate",
      additionalNotes: "Pain limiting daily activities. Cannot take aspirin or ibuprofen due to allergy. Needs alternative.",
    },
  },

  // ============================================
  // SIMPLE/CLEAN PATIENT DEMOS
  // ============================================
  {
    label: "✅ Emily Johnson - LOW RISK (Clean Profile)",
    description: "Healthy young patient with simple complaint - no complications",
    riskPreview: "LOW RISK - Standard treatment appropriate",
    demonstratesFeature: "Baseline case: LLM provides standard recommendation, DB finds no issues",
    data: {
      firstName: "Emily",
      lastName: "Johnson",
      dateOfBirth: "1995-04-22",
      sex: "female",
      conditions: [],
      allergies: [],
      familyHistory: [],
      surgicalHistory: [],
      currentMedications: [],
      healthMetrics: {
        age: 29,
        weight: 62,
        height: 168,
        bloodPressureSystolic: 115,
        bloodPressureDiastolic: 72,
        heartRate: 68,
        bloodGlucose: 88,
      },
      lifestyle: {
        smokingStatus: "never",
        alcoholUse: "occasional",
        exerciseFrequency: "active",
        dietType: "Balanced diet",
        sleepHours: 8,
      },
      primaryComplaint: "Mild acne",
      complaintDuration: "2 months",
      complaintSeverity: "mild",
      additionalNotes: "Occasional breakouts on chin and forehead. Wants topical treatment options.",
    },
  },
  {
    label: "✅ David Park - LOW RISK (Healthy Male)",
    description: "Healthy male patient seeking hair loss treatment",
    riskPreview: "LOW RISK - Few complicating factors",
    demonstratesFeature: "Simple case: LLM recommends finasteride, DB confirms no issues",
    data: {
      firstName: "David",
      lastName: "Park",
      dateOfBirth: "1990-08-15",
      sex: "male",
      conditions: [],
      allergies: [],
      familyHistory: ["Male pattern baldness"],
      surgicalHistory: [],
      currentMedications: [],
      healthMetrics: {
        age: 34,
        weight: 78,
        height: 177,
        bloodPressureSystolic: 120,
        bloodPressureDiastolic: 75,
        heartRate: 65,
        bloodGlucose: 92,
      },
      lifestyle: {
        smokingStatus: "never",
        alcoholUse: "occasional",
        exerciseFrequency: "active",
        dietType: "High protein diet",
        sleepHours: 7,
      },
      primaryComplaint: "Hair loss - male pattern baldness",
      complaintDuration: "1 year",
      complaintSeverity: "mild",
      additionalNotes: "Receding hairline and thinning at crown. Father and grandfather had similar pattern.",
    },
  },
  {
    label: "✅ Jennifer White - LOW RISK (Simple Weight Loss)",
    description: "Healthy patient seeking weight management assistance",
    riskPreview: "LOW RISK - Appropriate for GLP-1 treatment",
    demonstratesFeature: "Standard case: LLM recommends semaglutide, DB confirms no contraindications",
    data: {
      firstName: "Jennifer",
      lastName: "White",
      dateOfBirth: "1988-02-10",
      sex: "female",
      conditions: ["Obesity (BMI 32)"],
      allergies: [],
      familyHistory: ["Obesity", "Type 2 Diabetes"],
      surgicalHistory: [],
      currentMedications: [],
      healthMetrics: {
        age: 36,
        weight: 92,
        height: 170,
        bloodPressureSystolic: 128,
        bloodPressureDiastolic: 82,
        heartRate: 78,
        bloodGlucose: 105,
      },
      lifestyle: {
        smokingStatus: "never",
        alcoholUse: "occasional",
        exerciseFrequency: "light",
        dietType: "Trying various diets",
        sleepHours: 6,
      },
      primaryComplaint: "Weight loss - difficulty losing weight",
      complaintDuration: "2 years",
      complaintSeverity: "moderate",
      additionalNotes: "Failed multiple diet attempts. Pre-diabetic range. Motivated for medical intervention.",
    },
  },

  // ============================================
  // COMPLEX MULTI-FACTOR DEMO
  // ============================================
  {
    label: "💀 George Miller - CRITICAL (Multiple Red Flags)",
    description: "Complex patient demonstrating multiple safety layers",
    riskPreview: "CRITICAL - Multiple interactions + contraindications + allergies",
    demonstratesFeature: "Full system demo: Drug interactions + Condition contraindications + Allergy cross-reactivity",
    data: {
      firstName: "George",
      lastName: "Miller",
      dateOfBirth: "1955-10-30",
      sex: "male",
      conditions: [
        "Unstable Angina",
        "Type 2 Diabetes",
        "Chronic Kidney Disease Stage 4",
        "Atrial Fibrillation",
        "GERD",
      ],
      allergies: ["ACE inhibitors (angioedema)", "Penicillin", "Contrast dye"],
      familyHistory: ["Heart disease", "Stroke", "Diabetes"],
      surgicalHistory: ["CABG (2020)", "Appendectomy (1985)"],
      currentMedications: [
        { name: "Isosorbide mononitrate", dosage: "30mg", frequency: "once daily" },
        { name: "Warfarin", dosage: "7.5mg", frequency: "once daily" },
        { name: "Metformin", dosage: "500mg", frequency: "twice daily" },
        { name: "Metoprolol", dosage: "50mg", frequency: "twice daily" },
        { name: "Omeprazole", dosage: "40mg", frequency: "once daily" },
        { name: "Clopidogrel", dosage: "75mg", frequency: "once daily" },
      ],
      healthMetrics: {
        age: 69,
        weight: 98,
        height: 175,
        bloodPressureSystolic: 148,
        bloodPressureDiastolic: 92,
        heartRate: 82,
        bloodGlucose: 180,
      },
      lifestyle: {
        smokingStatus: "former",
        alcoholUse: "none",
        exerciseFrequency: "sedentary",
        dietType: "Diabetic renal diet",
        sleepHours: 5,
      },
      primaryComplaint: "Erectile dysfunction",
      complaintDuration: "1 year",
      complaintSeverity: "severe",
      additionalNotes: "Multiple health issues. Wife concerned about his depression. Wants treatment options despite complex history.",
    },
  },
];

export const commonConditions = [
  "Type 2 Diabetes",
  "Type 1 Diabetes",
  "Hypertension",
  "Hyperlipidemia",
  "Coronary Artery Disease",
  "Heart Failure",
  "Atrial Fibrillation",
  "Chronic Kidney Disease",
  "Asthma",
  "COPD",
  "Depression",
  "Anxiety",
  "Hypothyroidism",
  "Hyperthyroidism",
  "GERD",
  "Osteoarthritis",
  "Rheumatoid Arthritis",
  "Migraine",
  "Epilepsy",
  "Obesity",
  "Sleep Apnea",
  "BPH (Benign Prostatic Hyperplasia)",
  "Glaucoma",
  "History of Stroke",
  "History of DVT/PE",
  "Liver Disease",
  "Recent Myocardial Infarction",
  "Unstable Angina",
  "Severe Heart Failure",
];

export const commonAllergies = [
  "Penicillin",
  "Sulfa drugs",
  "Aspirin",
  "NSAIDs",
  "ACE inhibitors",
  "Codeine",
  "Morphine",
  "Latex",
  "Iodine/Contrast dye",
  "Shellfish",
  "Peanuts",
  "Tree nuts",
  "Eggs",
  "Dairy",
  "Gluten",
  "Soy",
];

export const primaryComplaints = [
  "Erectile dysfunction",
  "Hair loss (male pattern)",
  "Hair loss (female pattern)",
  "Weight loss assistance",
  "Weight gain/muscle building",
  "Anxiety symptoms",
  "Depression symptoms",
  "Insomnia",
  "Chronic pain",
  "Skin conditions (acne)",
  "Skin conditions (anti-aging)",
  "Low testosterone symptoms",
  "Menopause symptoms",
  "Birth control consultation",
  "Cold/flu symptoms",
  "Allergies",
  "Sinus infection",
  "Joint pain management",
];
