import { PatientData } from "@/shared/types/patient";

// Sample patients that demonstrate various risk scenarios
export const samplePatients: {
  label: string;
  description: string;
  riskPreview: string;
  data: PatientData;
}[] = [
  {
    label: "John Smith - High Risk (Multiple Interactions)",
    description:
      "Elderly patient with hypertension, diabetes, and multiple medications",
    riskPreview: "HIGH RISK - Drug interactions expected",
    data: {
      firstName: "John",
      lastName: "Smith",
      dateOfBirth: "1955-03-15",
      sex: "male",
      conditions: [
        "Type 2 Diabetes",
        "Hypertension",
        "Chronic Kidney Disease Stage 3",
        "Atrial Fibrillation",
        "Hyperlipidemia",
      ],
      allergies: ["Penicillin", "Sulfa drugs"],
      familyHistory: ["Heart disease", "Stroke", "Diabetes"],
      surgicalHistory: [
        "Appendectomy (1990)",
        "Coronary stent placement (2020)",
      ],
      currentMedications: [
        { name: "Metformin", dosage: "1000mg", frequency: "twice daily" },
        { name: "Lisinopril", dosage: "20mg", frequency: "once daily" },
        { name: "Warfarin", dosage: "5mg", frequency: "once daily" },
        {
          name: "Atorvastatin",
          dosage: "40mg",
          frequency: "once daily at bedtime",
        },
        { name: "Metoprolol", dosage: "50mg", frequency: "twice daily" },
        { name: "Aspirin", dosage: "81mg", frequency: "once daily" },
      ],
      healthMetrics: {
        age: 69,
        weight: 95,
        height: 175,
        bloodPressureSystolic: 145,
        bloodPressureDiastolic: 92,
        heartRate: 78,
        bloodGlucose: 165,
      },
      lifestyle: {
        smokingStatus: "former",
        alcoholUse: "occasional",
        exerciseFrequency: "light",
        dietType: "Low sodium diet",
        sleepHours: 6,
      },
      primaryComplaint: "Erectile dysfunction",
      complaintDuration: "6 months",
      complaintSeverity: "moderate",
      additionalNotes:
        "Patient reports this is affecting quality of life and relationship. Interested in treatment options.",
    },
  },
  {
    label: "Maria Garcia - Medium Risk (Contraindications)",
    description: "Middle-aged woman with anxiety, migraine history",
    riskPreview: "MEDIUM RISK - Contraindications present",
    data: {
      firstName: "Maria",
      lastName: "Garcia",
      dateOfBirth: "1980-07-22",
      sex: "female",
      conditions: [
        "Generalized Anxiety Disorder",
        "Migraine with aura",
        "Hypothyroidism",
        "History of Deep Vein Thrombosis",
      ],
      allergies: ["Ibuprofen", "Latex"],
      familyHistory: ["Breast cancer", "Thyroid disease"],
      surgicalHistory: ["Thyroidectomy (partial, 2018)"],
      currentMedications: [
        { name: "Sertraline", dosage: "100mg", frequency: "once daily" },
        {
          name: "Levothyroxine",
          dosage: "75mcg",
          frequency: "once daily before breakfast",
        },
        {
          name: "Sumatriptan",
          dosage: "50mg",
          frequency: "as needed for migraines",
        },
        {
          name: "Rivaroxaban",
          dosage: "20mg",
          frequency: "once daily with food",
        },
      ],
      healthMetrics: {
        age: 44,
        weight: 68,
        height: 162,
        bloodPressureSystolic: 118,
        bloodPressureDiastolic: 76,
        heartRate: 72,
        bloodGlucose: 95,
      },
      lifestyle: {
        smokingStatus: "never",
        alcoholUse: "occasional",
        exerciseFrequency: "moderate",
        dietType: "Mediterranean diet",
        sleepHours: 7,
      },
      primaryComplaint: "Hair loss - female pattern hair loss",
      complaintDuration: "1 year",
      complaintSeverity: "moderate",
      additionalNotes:
        "Noticed thinning primarily at the crown. Thyroid levels are stable. Wants to explore treatment options.",
    },
  },
  {
    label: "David Chen - Low Risk (Healthy Patient)",
    description: "Young healthy male with minor complaint",
    riskPreview: "LOW RISK - Few complicating factors",
    data: {
      firstName: "David",
      lastName: "Chen",
      dateOfBirth: "1995-11-08",
      sex: "male",
      conditions: ["Seasonal allergies"],
      allergies: ["Pollen", "Dust mites"],
      familyHistory: [],
      surgicalHistory: [],
      currentMedications: [
        {
          name: "Cetirizine",
          dosage: "10mg",
          frequency: "once daily as needed",
        },
      ],
      healthMetrics: {
        age: 29,
        weight: 75,
        height: 178,
        bloodPressureSystolic: 118,
        bloodPressureDiastolic: 72,
        heartRate: 65,
        bloodGlucose: 88,
      },
      lifestyle: {
        smokingStatus: "never",
        alcoholUse: "occasional",
        exerciseFrequency: "active",
        dietType: "Balanced diet",
        sleepHours: 8,
      },
      primaryComplaint: "Weight loss - wants to lose 10 pounds",
      complaintDuration: "3 months",
      complaintSeverity: "mild",
      additionalNotes:
        "Looking for assistance with weight management. Currently at healthy BMI but wants to be more fit for upcoming athletic event.",
    },
  },
  {
    label: "Robert Johnson - Critical Risk (Severe Allergies)",
    description: "Patient with multiple severe allergies and complex history",
    riskPreview:
      "CRITICAL RISK - Multiple severe allergies, careful medication selection required",
    data: {
      firstName: "Robert",
      lastName: "Johnson",
      dateOfBirth: "1968-04-30",
      sex: "male",
      conditions: [
        "Coronary Artery Disease",
        "Heart Failure (EF 35%)",
        "Type 2 Diabetes",
        "Peripheral Neuropathy",
        "Chronic Pain Syndrome",
        "Depression",
      ],
      allergies: [
        "Penicillin (anaphylaxis)",
        "NSAIDs (GI bleeding)",
        "ACE inhibitors (angioedema)",
        "Codeine",
        "Metformin (lactic acidosis history)",
        "Contrast dye",
      ],
      familyHistory: ["Sudden cardiac death", "Diabetes", "Cancer"],
      surgicalHistory: ["CABG x3 (2019)", "ICD placement (2020)"],
      currentMedications: [
        { name: "Carvedilol", dosage: "25mg", frequency: "twice daily" },
        { name: "Losartan", dosage: "50mg", frequency: "once daily" },
        { name: "Furosemide", dosage: "40mg", frequency: "once daily" },
        {
          name: "Insulin Glargine",
          dosage: "30 units",
          frequency: "once daily at bedtime",
        },
        { name: "Gabapentin", dosage: "300mg", frequency: "three times daily" },
        { name: "Duloxetine", dosage: "60mg", frequency: "once daily" },
        { name: "Clopidogrel", dosage: "75mg", frequency: "once daily" },
      ],
      healthMetrics: {
        age: 56,
        weight: 102,
        height: 180,
        bloodPressureSystolic: 138,
        bloodPressureDiastolic: 85,
        heartRate: 68,
        bloodGlucose: 185,
      },
      lifestyle: {
        smokingStatus: "former",
        alcoholUse: "none",
        exerciseFrequency: "sedentary",
        dietType: "Cardiac diet",
        sleepHours: 5,
      },
      primaryComplaint: "Erectile dysfunction - severe",
      complaintDuration: "2 years",
      complaintSeverity: "severe",
      additionalNotes:
        "ED worsened after cardiac surgery. Psychologically impacting patient. Has tried lifestyle modifications without success. Concerned about medication interactions with heart condition.",
    },
  },
  {
    label: "Sarah Williams - No Risk (Ideal Patient)",
    description: "Young healthy woman with no medical history - perfect test case",
    riskPreview: "NO RISK - Clean medical profile",
    data: {
      firstName: "Sarah",
      lastName: "Williams",
      dateOfBirth: "1998-06-15",
      sex: "female",
      conditions: [],
      allergies: [],
      familyHistory: [],
      surgicalHistory: [],
      currentMedications: [],
      healthMetrics: {
        age: 26,
        weight: 62,
        height: 165,
        bloodPressureSystolic: 112,
        bloodPressureDiastolic: 70,
        heartRate: 68,
        bloodGlucose: 85,
      },
      lifestyle: {
        smokingStatus: "never",
        alcoholUse: "occasional",
        exerciseFrequency: "active",
        dietType: "Balanced whole foods",
        sleepHours: 8,
      },
      primaryComplaint: "Skin conditions (acne)",
      complaintDuration: "2 months",
      complaintSeverity: "mild",
      additionalNotes:
        "Mild hormonal acne flare-up. No previous treatments tried. Looking for first-line treatment options.",
    },
  },
];

export const commonConditions = [
  "Type 2 Diabetes",
  "Type 1 Diabetes",
  "Hypertension",
  "Hyperlipidemia",
  "Coronary Artery Disease",
  "Heart Failure",
  "Atrial Fibrillation",
  "Chronic Kidney Disease",
  "Asthma",
  "COPD",
  "Depression",
  "Anxiety",
  "Hypothyroidism",
  "Hyperthyroidism",
  "GERD",
  "Osteoarthritis",
  "Rheumatoid Arthritis",
  "Migraine",
  "Epilepsy",
  "Obesity",
  "Sleep Apnea",
  "BPH (Benign Prostatic Hyperplasia)",
  "Glaucoma",
  "History of Stroke",
  "History of DVT/PE",
  "Liver Disease",
  "HIV/AIDS",
];

export const commonAllergies = [
  "Penicillin",
  "Sulfa drugs",
  "Aspirin",
  "NSAIDs",
  "ACE inhibitors",
  "Codeine",
  "Morphine",
  "Latex",
  "Iodine/Contrast dye",
  "Shellfish",
  "Peanuts",
  "Tree nuts",
  "Eggs",
  "Dairy",
  "Gluten",
  "Soy",
];

export const primaryComplaints = [
  "Erectile dysfunction",
  "Hair loss (male pattern)",
  "Hair loss (female pattern)",
  "Weight loss assistance",
  "Weight gain/muscle building",
  "Anxiety symptoms",
  "Depression symptoms",
  "Insomnia",
  "Chronic pain",
  "Skin conditions (acne)",
  "Skin conditions (anti-aging)",
  "Low testosterone symptoms",
  "Menopause symptoms",
  "Birth control consultation",
  "Cold/flu symptoms",
  "Allergies",
];
